import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import Providers from './providers';
import { ToastProvider } from '@/components/providers/toaster.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'My Start-up App',
  description: 'Generated by John Paul'
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <Providers>
            <ToastProvider />
            {children}
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
